// biome-ignore-all lint/style/useFilenamingConvention: Live integration inventory uses this suffix.
import { randomUUID } from "node:crypto";
import { PrismaPg } from "@prisma/adapter-pg";
import { config } from "dotenv";
import type { ClerkOrgId, OrganisationId } from "@repo/core";
import { afterAll, describe, expect, test, vi } from "vitest";
import { PrismaClient } from "./generated/client";
import { scopedQuery } from "./src/tenant-query";

config({ path: new URL("./.env", import.meta.url).pathname });
vi.mock("server-only", () => ({}));

const databaseUrl = process.env.DATABASE_URL;
const authorised =
  process.env.ALLOW_TRANSACTION_ROLLBACK_TESTS ===
  "I_ACKNOWLEDGE_TRANSACTION_ROLLBACK";
if (!databaseUrl || !authorised) {
  throw new Error(
    "Live rollback tests require the configured database and explicit acknowledgement"
  );
}
const identity = new URL(databaseUrl);
const expectedIdentity = {
  database: process.env.TC_EXPECTED_DATABASE_NAME,
  hostname: process.env.TC_EXPECTED_DATABASE_HOST,
  role: process.env.TC_EXPECTED_DATABASE_ROLE,
};
if (!(expectedIdentity.database && expectedIdentity.hostname && expectedIdentity.role)) {
  throw new Error("Protected expected database identity inputs are required");
}
if (
  identity.hostname !== expectedIdentity.hostname ||
  decodeURIComponent(identity.pathname.slice(1)) !== expectedIdentity.database ||
  decodeURIComponent(identity.username) !== expectedIdentity.role
) {
  throw new Error("Configured database identity does not match the reviewed Neon target");
}
const describeLive = describe;
// These IDs are generated by the controlled fixture itself and are used only
// after the exact live target and explicit rollback authority are validated.
const fixtureClerkOrgId = (value: string): ClerkOrgId => value as ClerkOrgId;
const fixtureOrganisationId = (value: string): OrganisationId =>
  value as OrganisationId;
const database = databaseUrl
  ? new PrismaClient({ adapter: new PrismaPg({ connectionString: databaseUrl }) })
  : undefined;

afterAll(async () => {
  await database?.$disconnect();
});

describeLive("transaction-bound live tenant invariants", () => {
  test("proves two-key isolation and leaves no committed fixture", async () => {
    if (!database) {
      throw new Error("Live database was not configured");
    }
    const runId = randomUUID();
    const clerkOrgA = `org_release_${runId}_a`;
    const clerkOrgB = `org_release_${runId}_b`;
    const organisationA = randomUUID();
    const organisationB = randomUUID();
    const teamA = randomUUID();
    const teamB = randomUUID();
    const rollback = new Error("ROLLBACK_RELEASE_FIXTURE");

    await expect(
      database.$transaction(async (transaction) => {
        await transaction.organisation.createMany({
          data: [
            { clerk_org_id: clerkOrgA, country_code: "AU", id: organisationA, name: "Release fixture A" },
            { clerk_org_id: clerkOrgB, country_code: "AU", id: organisationB, name: "Release fixture B" },
          ],
        });
        await transaction.team.createMany({
          data: [
            { clerk_org_id: clerkOrgA, id: teamA, name: "Release team A", organisation_id: organisationA },
            { clerk_org_id: clerkOrgB, id: teamB, name: "Release team B", organisation_id: organisationB },
          ],
        });
        const leaked = await transaction.team.findFirst({
          where: {
            ...scopedQuery(
              fixtureClerkOrgId(clerkOrgA),
              fixtureOrganisationId(organisationA)
            ),
            id: teamB,
          },
        });
        const owned = await transaction.team.findFirst({
          where: {
            ...scopedQuery(
              fixtureClerkOrgId(clerkOrgA),
              fixtureOrganisationId(organisationA)
            ),
            id: teamA,
          },
        });
        expect(leaked).toBeNull();
        expect(owned?.id).toBe(teamA);
        throw rollback;
      })
    ).rejects.toBe(rollback);

    await expect(
      database.organisation.count({
        where: { clerk_org_id: { in: [clerkOrgA, clerkOrgB] } },
      })
    ).resolves.toBe(0);
  });

  test("enforces one Xero connection per Organisation and rolls back", async () => {
    if (!database) {
      throw new Error("Live database was not configured");
    }
    const clerkOrgId = `org_release_${randomUUID()}`;
    const organisationId = randomUUID();
    const firstConnectionId = randomUUID();
    const secondConnectionId = randomUUID();
    const rollback = new Error("ROLLBACK_RELEASE_CONSTRAINT_FIXTURE");
    let failure: unknown;

    try {
      await database.$transaction(async (transaction) => {
        await transaction.organisation.create({
          data: {
            clerk_org_id: clerkOrgId,
            country_code: "AU",
            id: organisationId,
            name: "Release constraint fixture",
          },
        });
        await transaction.xeroConnection.create({
          data: {
            clerk_org_id: clerkOrgId,
            expires_at: new Date("2027-01-01T00:00:00.000Z"),
            id: firstConnectionId,
            organisation_id: organisationId,
          },
        });
        await transaction.xeroConnection.create({
          data: {
            clerk_org_id: clerkOrgId,
            expires_at: new Date("2027-01-01T00:00:00.000Z"),
            id: secondConnectionId,
            organisation_id: organisationId,
          },
        });
        throw rollback;
      });
    } catch (error) {
      failure = error;
    }

    expect(failure).not.toBe(rollback);
    expect(failure).toMatchObject({ code: "P2002" });
    await expect(
      database.organisation.count({
        where: { clerk_org_id: clerkOrgId, id: organisationId },
      })
    ).resolves.toBe(0);
    await expect(
      database.xeroConnection.count({
        where: {
          clerk_org_id: clerkOrgId,
          id: { in: [firstConnectionId, secondConnectionId] },
          organisation_id: organisationId,
        },
      })
    ).resolves.toBe(0);
  });

  test("enforces feed slug uniqueness within a Clerk Organisation and rolls back", async () => {
    if (!database) {
      throw new Error("Live database was not configured");
    }
    const clerkOrgId = `org_release_${randomUUID()}`;
    const organisationId = randomUUID();
    const feedIds = [randomUUID(), randomUUID()];
    const rollback = new Error("ROLLBACK_RELEASE_FEED_FIXTURE");
    let failure: unknown;

    try {
      await database.$transaction(async (transaction) => {
        await transaction.organisation.create({
          data: {
            clerk_org_id: clerkOrgId,
            country_code: "AU",
            id: organisationId,
            name: "Release feed fixture",
          },
        });
        for (const id of feedIds) {
          await transaction.feed.create({
            data: {
              clerk_org_id: clerkOrgId,
              id,
              name: "Release feed",
              organisation_id: organisationId,
              slug: "release-feed",
            },
          });
        }
        throw rollback;
      });
    } catch (error) {
      failure = error;
    }

    expect(failure).not.toBe(rollback);
    expect(failure).toMatchObject({ code: "P2002" });
    await expect(
      database.feed.count({
        where: {
          clerk_org_id: clerkOrgId,
          id: { in: feedIds },
          organisation_id: organisationId,
        },
      })
    ).resolves.toBe(0);
    await expect(
      database.organisation.count({
        where: { clerk_org_id: clerkOrgId, id: organisationId },
      })
    ).resolves.toBe(0);
  });
});
