// biome-ignore-all lint/style/useFilenamingConvention: Live integration inventory uses this suffix.
import { PrismaPg } from "@prisma/adapter-pg";
import type { ClerkOrgId, OrganisationId } from "@repo/core";
import { afterAll, describe, expect, test, vi } from "vitest";
import { PrismaClient } from "./generated/client";
import { allocateLiveTestFixture } from "./src/live-test-fixture";
import { scopedQuery } from "./src/tenant-query";

vi.mock("server-only", () => ({}));

const fixture = allocateLiveTestFixture(
  "packages/database/live-rollback.integration.test.ts"
);
const databaseUrl = process.env.DATABASE_URL as string;
// These IDs are generated by the controlled fixture itself and are used only
// after the exact live target and explicit rollback authority are validated.
const fixtureClerkOrgId = (value: string): ClerkOrgId => value as ClerkOrgId;
const fixtureOrganisationId = (value: string): OrganisationId =>
  value as OrganisationId;
const database = new PrismaClient({
  adapter: new PrismaPg({ connectionString: databaseUrl }),
});

afterAll(async () => {
  await database.$disconnect();
});

describe("transaction-bound live tenant invariants", () => {
  test("proves two-key isolation and leaves no committed fixture", async () => {
    const clerkOrgA = fixture.tenants[0]?.clerkOrgId as string;
    const clerkOrgB = fixture.tenants[1]?.clerkOrgId as string;
    const organisationA = fixture.tenants[0]?.organisationId as string;
    const organisationB = fixture.tenants[1]?.organisationId as string;
    const teamA = fixture.id("team", 0);
    const teamB = fixture.id("team", 1);
    const rollback = new Error("ROLLBACK_RELEASE_FIXTURE");

    await expect(
      database.$transaction(async (transaction) => {
        await transaction.organisation.createMany({
          data: [
            {
              clerk_org_id: clerkOrgA,
              country_code: "AU",
              id: organisationA,
              name: "Release fixture A",
            },
            {
              clerk_org_id: clerkOrgB,
              country_code: "AU",
              id: organisationB,
              name: "Release fixture B",
            },
          ],
        });
        await transaction.team.createMany({
          data: [
            {
              clerk_org_id: clerkOrgA,
              id: teamA,
              name: "Release team A",
              organisation_id: organisationA,
            },
            {
              clerk_org_id: clerkOrgB,
              id: teamB,
              name: "Release team B",
              organisation_id: organisationB,
            },
          ],
        });
        const leaked = await transaction.team.findFirst({
          where: {
            ...scopedQuery(
              fixtureClerkOrgId(clerkOrgA),
              fixtureOrganisationId(organisationA)
            ),
            id: teamB,
          },
        });
        const owned = await transaction.team.findFirst({
          where: {
            ...scopedQuery(
              fixtureClerkOrgId(clerkOrgA),
              fixtureOrganisationId(organisationA)
            ),
            id: teamA,
          },
        });
        expect(leaked).toBeNull();
        expect(owned?.id).toBe(teamA);
        throw rollback;
      })
    ).rejects.toBe(rollback);

    await expect(
      database.organisation.count({
        where: { clerk_org_id: { in: [clerkOrgA, clerkOrgB] } },
      })
    ).resolves.toBe(0);
  });

  test("enforces one Xero connection per Organisation and rolls back", async () => {
    if (!database) {
      throw new Error("Live database was not configured");
    }
    const clerkOrgId = fixture.tenants[0]?.clerkOrgId as string;
    const organisationId = fixture.tenants[0]?.organisationId as string;
    const firstConnectionId = fixture.id("connection", 0);
    const secondConnectionId = fixture.id("connection", 1);
    const rollback = new Error("ROLLBACK_RELEASE_CONSTRAINT_FIXTURE");
    let failure: unknown;

    try {
      await database.$transaction(async (transaction) => {
        await transaction.organisation.create({
          data: {
            clerk_org_id: clerkOrgId,
            country_code: "AU",
            id: organisationId,
            name: "Release constraint fixture",
          },
        });
        await transaction.xeroConnection.create({
          data: {
            clerk_org_id: clerkOrgId,
            expires_at: new Date("2027-01-01T00:00:00.000Z"),
            id: firstConnectionId,
            organisation_id: organisationId,
          },
        });
        await transaction.xeroConnection.create({
          data: {
            clerk_org_id: clerkOrgId,
            expires_at: new Date("2027-01-01T00:00:00.000Z"),
            id: secondConnectionId,
            organisation_id: organisationId,
          },
        });
        throw rollback;
      });
    } catch (error) {
      failure = error;
    }

    expect(failure).not.toBe(rollback);
    expect(failure).toMatchObject({ code: "P2002" });
    await expect(
      database.organisation.count({
        where: { clerk_org_id: clerkOrgId, id: organisationId },
      })
    ).resolves.toBe(0);
    await expect(
      database.xeroConnection.count({
        where: {
          clerk_org_id: clerkOrgId,
          id: { in: [firstConnectionId, secondConnectionId] },
          organisation_id: organisationId,
        },
      })
    ).resolves.toBe(0);
  });

  test("enforces feed slug uniqueness within a Clerk Organisation and rolls back", async () => {
    if (!database) {
      throw new Error("Live database was not configured");
    }
    const clerkOrgId = fixture.tenants[1]?.clerkOrgId as string;
    const organisationId = fixture.tenants[1]?.organisationId as string;
    const feedIds = [fixture.id("feed", 0), fixture.id("feed", 1)];
    const rollback = new Error("ROLLBACK_RELEASE_FEED_FIXTURE");
    let failure: unknown;

    try {
      await database.$transaction(async (transaction) => {
        await transaction.organisation.create({
          data: {
            clerk_org_id: clerkOrgId,
            country_code: "AU",
            id: organisationId,
            name: "Release feed fixture",
          },
        });
        for (const id of feedIds) {
          await transaction.feed.create({
            data: {
              clerk_org_id: clerkOrgId,
              id,
              name: "Release feed",
              organisation_id: organisationId,
              slug: "release-feed",
            },
          });
        }
        throw rollback;
      });
    } catch (error) {
      failure = error;
    }

    expect(failure).not.toBe(rollback);
    expect(failure).toMatchObject({ code: "P2002" });
    await expect(
      database.feed.count({
        where: {
          clerk_org_id: clerkOrgId,
          id: { in: feedIds },
          organisation_id: organisationId,
        },
      })
    ).resolves.toBe(0);
    await expect(
      database.organisation.count({
        where: { clerk_org_id: clerkOrgId, id: organisationId },
      })
    ).resolves.toBe(0);
  });
});
