import { createHmac, hkdfSync } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { encryptXeroToken } from "../crypto/tokens";

vi.mock("server-only", () => ({}));

const dbMock = vi.hoisted(() => ({
  $queryRaw: vi.fn(),
  $transaction: vi.fn(),
  organisation: {
    create: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn(),
  },
  xeroConnection: {
    findFirst: vi.fn(),
    update: vi.fn(),
    updateMany: vi.fn(),
    upsert: vi.fn(),
  },
  xeroOAuthSession: {
    create: vi.fn(),
    findFirst: vi.fn(),
    update: vi.fn(),
    updateMany: vi.fn(),
  },
  xeroTenant: {
    findFirst: vi.fn(),
    upsert: vi.fn(),
  },
}));
const feedMock = vi.hoisted(() => ({
  ensureDefaultCalendarFeed: vi.fn(),
}));
const availabilityMock = vi.hoisted(() => ({
  ensureDefaultPublicHolidaysForOrganisation: vi.fn(),
}));
vi.mock("@repo/database", () => ({
  database: dbMock,
}));
vi.mock("@repo/feeds", () => feedMock);
vi.mock("@repo/availability", () => availabilityMock);

const {
  buildXeroOAuthStartUrl,
  completeXeroOAuth,
  completeXeroTenantSelection,
  disconnectXeroOAuthConnection,
  ensureFreshXeroConnection,
  isLocalApplicationPath,
  isPreviewDeployment,
  markXeroConnectionStale,
  refreshXeroOAuthConnection,
  scrubInactiveXeroOAuthSessionCredentials,
  xeroConnectionRefreshDecision,
} = await import("./service");

const ORIGINAL_ENV = { ...process.env };

interface OAuthTestStatePayload {
  clerkOrgId: string;
  issuedAt: number;
  nonce: string;
  organisationId: null | string;
  returnTo: string;
  userId: null | string;
}

function readStatePayload(redirectUrl: string): OAuthTestStatePayload {
  const state = new URL(redirectUrl).searchParams.get("state");
  const [encoded] = (state ?? "").split(".");
  if (!encoded) {
    throw new Error("Expected signed OAuth state.");
  }

  // The value is generated by the service under test and this helper only
  // exposes its JSON payload for assertions.
  return JSON.parse(
    Buffer.from(encoded, "base64url").toString("utf8")
  ) as OAuthTestStatePayload;
}

function signTestState(payload: OAuthTestStatePayload): string {
  const encoded = Buffer.from(JSON.stringify(payload)).toString("base64url");
  const signingKey = Buffer.from(
    hkdfSync(
      "sha256",
      "client-secret",
      "",
      "team-calendar:xero-oauth-state:v1",
      32
    )
  );
  const signature = createHmac("sha256", signingKey)
    .update(encoded)
    .digest("base64url");
  return `${encoded}.${signature}`;
}

function buildStoredTokenFields() {
  const accessToken = encryptXeroToken("access-token");
  const refreshToken = encryptXeroToken("refresh-token");

  return {
    access_token_auth_tag: accessToken.authTag,
    access_token_encrypted: accessToken.encrypted,
    access_token_iv: accessToken.iv,
    refresh_token_auth_tag: refreshToken.authTag,
    refresh_token_encrypted: refreshToken.encrypted,
    refresh_token_iv: refreshToken.iv,
  };
}

beforeEach(() => {
  process.env.XERO_CLIENT_ID = "client-id";
  process.env.XERO_CLIENT_SECRET = "client-secret";
  process.env.XERO_REDIRECT_URI =
    "https://api.example.com/api/xero/oauth/callback";
  process.env.XERO_TOKEN_ENCRYPTION_KEY = Buffer.alloc(32).toString("base64");
  delete process.env.VERCEL_ENV;
  dbMock.$queryRaw.mockReset();
  dbMock.$queryRaw.mockResolvedValue([]);
  dbMock.$transaction.mockReset();
  dbMock.$transaction.mockImplementation((callback) => callback(dbMock));
  dbMock.organisation.create.mockReset();
  dbMock.organisation.findFirst.mockReset();
  dbMock.organisation.findMany.mockReset();
  dbMock.xeroConnection.findFirst.mockReset();
  dbMock.xeroConnection.upsert.mockReset();
  dbMock.xeroConnection.update.mockReset();
  dbMock.xeroConnection.updateMany.mockReset();
  dbMock.xeroConnection.updateMany.mockResolvedValue({ count: 1 });
  dbMock.xeroOAuthSession.findFirst.mockReset();
  dbMock.xeroOAuthSession.create.mockReset();
  dbMock.xeroOAuthSession.update.mockReset();
  dbMock.xeroOAuthSession.updateMany.mockReset();
  dbMock.xeroOAuthSession.updateMany.mockResolvedValue({ count: 1 });
  dbMock.xeroTenant.upsert.mockReset();
  dbMock.xeroTenant.findFirst.mockReset();
  dbMock.xeroTenant.findFirst.mockResolvedValue(null);
  feedMock.ensureDefaultCalendarFeed.mockReset();
  feedMock.ensureDefaultCalendarFeed.mockResolvedValue({
    ok: true,
    value: { created: true, feedId: "feed_1" },
  });
  availabilityMock.ensureDefaultPublicHolidaysForOrganisation.mockReset();
  availabilityMock.ensureDefaultPublicHolidaysForOrganisation.mockResolvedValue(
    {
      ok: true,
      value: {
        importedCount: 2,
        importedYears: [2026, 2027],
        skippedCount: 0,
        skippedYears: [],
      },
    }
  );
});

afterEach(() => {
  process.env = { ...ORIGINAL_ENV };
  vi.unstubAllGlobals();
});

describe("isPreviewDeployment", () => {
  it("is true only on a Vercel preview deployment", () => {
    process.env.VERCEL_ENV = "preview";
    expect(isPreviewDeployment()).toBe(true);

    process.env.VERCEL_ENV = "production";
    expect(isPreviewDeployment()).toBe(false);

    delete process.env.VERCEL_ENV;
    expect(isPreviewDeployment()).toBe(false);
  });
});

describe("buildXeroOAuthStartUrl", () => {
  it("disables Xero connect on preview deployments", () => {
    process.env.VERCEL_ENV = "preview";

    const result = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("connect_disabled");
    }
  });

  it("returns oauth_not_configured when credentials are missing", () => {
    delete process.env.XERO_CLIENT_ID;
    delete process.env.XERO_CLIENT_SECRET;

    const result = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("oauth_not_configured");
    }
  });

  it("fails closed when verifying state without the client secret", async () => {
    const start = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });
    expect(start.ok).toBe(true);
    if (!start.ok) {
      return;
    }

    const redirectUrl = new URL(start.value.redirectUrl);
    const state = redirectUrl.searchParams.get("state");
    expect(state).toBeTruthy();

    const previousSecret = process.env.XERO_CLIENT_SECRET;
    delete process.env.XERO_CLIENT_SECRET;

    try {
      const result = await completeXeroOAuth({
        code: "authorisation-code",
        nonce: start.value.nonce,
        state: state ?? "",
      });

      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe("oauth_not_configured");
      }
    } finally {
      process.env.XERO_CLIENT_SECRET = previousSecret;
    }
  });

  it("uses the pre-registered redirect URI when configured", () => {
    const result = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });

    expect(result.ok).toBe(true);
    if (result.ok) {
      const redirectUrl = new URL(result.value.redirectUrl);
      expect(redirectUrl.searchParams.get("redirect_uri")).toBe(
        "https://api.example.com/api/xero/oauth/callback"
      );
    }
  });

  it("signs the default local return path", () => {
    const result = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });

    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(readStatePayload(result.value.redirectUrl).returnTo).toBe(
        "/settings/integrations/xero"
      );
    }
  });

  it("preserves a valid local return path with a query and fragment", () => {
    const returnTo = "/calendar?team=people#upcoming";
    const result = buildXeroOAuthStartUrl({
      clerkOrgId: "org_1",
      returnTo,
    });

    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(readStatePayload(result.value.redirectUrl).returnTo).toBe(
        returnTo
      );
    }
  });

  it.each([
    "https://attacker.example/path",
    "http://attacker.example/path",
    "//attacker.example/path",
    "/\\attacker.example/path",
    "/settings\n/integrations",
  ])("rejects the unsafe return path %j", (returnTo) => {
    const result = buildXeroOAuthStartUrl({
      clerkOrgId: "org_1",
      returnTo,
    });

    expect(result).toMatchObject({
      error: { code: "invalid_state" },
      ok: false,
    });
  });
});

describe("completeXeroOAuth", () => {
  it("records the current binding generation for an existing payroll entity", async () => {
    const start = buildXeroOAuthStartUrl({
      clerkOrgId: "org_1",
      organisationId: "90000000-0000-4000-8000-000000000002",
    });
    expect(start.ok).toBe(true);
    if (!start.ok) {
      return;
    }
    dbMock.xeroTenant.findFirst.mockResolvedValueOnce({
      binding_generation: 7,
    });
    dbMock.xeroOAuthSession.create.mockResolvedValueOnce({ id: "session_1" });
    vi.stubGlobal(
      "fetch",
      vi
        .fn()
        .mockResolvedValueOnce(
          Response.json({
            access_token: "access-token",
            expires_in: 1800,
            refresh_token: "refresh-token",
          })
        )
        .mockResolvedValueOnce(Response.json([]))
    );

    const result = await completeXeroOAuth({
      code: "authorisation-code",
      nonce: start.value.nonce,
      state: new URL(start.value.redirectUrl).searchParams.get("state") ?? "",
    });

    expect(result.ok).toBe(true);
    expect(dbMock.xeroTenant.findFirst).toHaveBeenCalledWith({
      select: { binding_generation: true },
      where: {
        clerk_org_id: "org_1",
        organisation_id: "90000000-0000-4000-8000-000000000002",
      },
    });
    expect(dbMock.xeroOAuthSession.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ expected_binding_generation: 7 }),
      })
    );
  });

  it("stores the Xero authorisation connection id in the pending session", async () => {
    const start = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });
    expect(start.ok).toBe(true);
    if (!start.ok) {
      return;
    }

    const state = new URL(start.value.redirectUrl).searchParams.get("state");
    dbMock.xeroOAuthSession.create.mockResolvedValueOnce({ id: "session_1" });
    const fetchSpy = vi
      .fn()
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            access_token: "access-token",
            expires_in: 1800,
            refresh_token: "refresh-token",
          }),
          { headers: { "Content-Type": "application/json" }, status: 200 }
        )
      )
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify([
            {
              id: "xero-connection-1",
              tenantId: "xero-tenant-1",
              tenantName: "Acme Payroll",
            },
          ]),
          { headers: { "Content-Type": "application/json" }, status: 200 }
        )
      );
    vi.stubGlobal("fetch", fetchSpy);

    const result = await completeXeroOAuth({
      code: "authorisation-code",
      nonce: start.value.nonce,
      state: state ?? "",
    });

    expect(result).toMatchObject({
      ok: true,
      value: { sessionId: "session_1" },
    });
    expect(dbMock.xeroOAuthSession.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          available_tenants_json: {
            tenants: [
              {
                connectionId: "xero-connection-1",
                tenantId: "xero-tenant-1",
                tenantName: "Acme Payroll",
              },
            ],
          },
        }),
      })
    );
  });

  it("rejects a missing nonce before exchanging the authorisation code", async () => {
    const start = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });
    expect(start.ok).toBe(true);
    if (!start.ok) {
      return;
    }

    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);
    const result = await completeXeroOAuth({
      code: "authorisation-code",
      nonce: null,
      state: new URL(start.value.redirectUrl).searchParams.get("state") ?? "",
    });

    expect(result).toMatchObject({
      error: { code: "invalid_state" },
      ok: false,
    });
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it("rejects a mismatched nonce before exchanging the authorisation code", async () => {
    const start = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });
    expect(start.ok).toBe(true);
    if (!start.ok) {
      return;
    }

    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);
    const result = await completeXeroOAuth({
      code: "authorisation-code",
      nonce: "mismatched-nonce",
      state: new URL(start.value.redirectUrl).searchParams.get("state") ?? "",
    });

    expect(result).toMatchObject({
      error: { code: "invalid_state" },
      ok: false,
    });
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it("replaces an unsafe return path from legacy signed state", async () => {
    const start = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });
    expect(start.ok).toBe(true);
    if (!start.ok) {
      return;
    }

    const legacyState = signTestState({
      ...readStatePayload(start.value.redirectUrl),
      returnTo: "https://attacker.example/path",
    });

    dbMock.xeroOAuthSession.create.mockResolvedValueOnce({ id: "session_1" });
    vi.stubGlobal(
      "fetch",
      vi
        .fn()
        .mockResolvedValueOnce(
          Response.json({
            access_token: "access-token",
            expires_in: 1800,
            refresh_token: "refresh-token",
          })
        )
        .mockResolvedValueOnce(Response.json([]))
    );

    const result = await completeXeroOAuth({
      code: "authorisation-code",
      nonce: start.value.nonce,
      state: legacyState,
    });

    expect(result.ok).toBe(true);
    expect(dbMock.xeroOAuthSession.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          return_to: "/settings/integrations/xero",
        }),
      })
    );
  });
});

describe("isLocalApplicationPath", () => {
  it("accepts local application paths only", () => {
    expect(isLocalApplicationPath("/calendar?team=people#upcoming")).toBe(true);
    expect(isLocalApplicationPath("/")).toBe(true);
    expect(isLocalApplicationPath("//attacker.example/path")).toBe(false);
    expect(isLocalApplicationPath("/\\attacker.example/path")).toBe(false);
    expect(isLocalApplicationPath("/settings\u0085/integrations")).toBe(false);
  });
});

describe("Xero OAuth state", () => {
  it("mints distinct states for identical inputs", () => {
    const first = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });
    const second = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });
    expect(first.ok && second.ok).toBe(true);
    if (!(first.ok && second.ok)) {
      return;
    }

    expect(first.value.nonce).not.toBe(second.value.nonce);
    expect(new URL(first.value.redirectUrl).searchParams.get("state")).not.toBe(
      new URL(second.value.redirectUrl).searchParams.get("state")
    );
  });

  it("rejects an eleven-minute-old state before exchanging the authorisation code", async () => {
    const nowSpy = vi.spyOn(Date, "now");
    nowSpy.mockReturnValueOnce(1_000_000).mockReturnValue(1_660_000);
    const start = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });
    expect(start.ok).toBe(true);
    if (!start.ok) {
      return;
    }

    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);
    const result = await completeXeroOAuth({
      code: "authorisation-code",
      nonce: start.value.nonce,
      state: new URL(start.value.redirectUrl).searchParams.get("state") ?? "",
    });

    expect(result).toMatchObject({
      error: { code: "invalid_state" },
      ok: false,
    });
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it("rejects a tampered state", async () => {
    const start = buildXeroOAuthStartUrl({ clerkOrgId: "org_1" });
    expect(start.ok).toBe(true);
    if (!start.ok) {
      return;
    }

    const state =
      new URL(start.value.redirectUrl).searchParams.get("state") ?? "";
    const [encoded, signature] = state.split(".");
    const result = await completeXeroOAuth({
      code: "authorisation-code",
      nonce: start.value.nonce,
      state: `${encoded.slice(0, -1)}x.${signature}`,
    });

    expect(result).toMatchObject({
      error: { code: "invalid_state" },
      ok: false,
    });
  });
});

describe("xeroConnectionRefreshDecision", () => {
  const now = new Date("2026-06-09T12:00:00.000Z");
  const base = {
    hasAccessToken: true,
    hasRefreshToken: true,
    revokedAt: null as Date | null,
    status: "active" as string | null,
  };

  it("uses the token as-is when it is comfortably before expiry", () => {
    const expiresAt = new Date(now.getTime() + 20 * 60 * 1000);
    expect(xeroConnectionRefreshDecision({ ...base, expiresAt }, now)).toBe(
      "active"
    );
  });

  it("refreshes when the token is within the expiry buffer", () => {
    const expiresAt = new Date(now.getTime() + 60 * 1000);
    expect(xeroConnectionRefreshDecision({ ...base, expiresAt }, now)).toBe(
      "refresh"
    );
  });

  it("refreshes when the token has already lapsed", () => {
    const expiresAt = new Date(now.getTime() - 60 * 1000);
    expect(xeroConnectionRefreshDecision({ ...base, expiresAt }, now)).toBe(
      "refresh"
    );
  });

  it("is inactive when within the buffer but no refresh token is stored", () => {
    const expiresAt = new Date(now.getTime() + 60 * 1000);
    expect(
      xeroConnectionRefreshDecision(
        { ...base, expiresAt, hasRefreshToken: false },
        now
      )
    ).toBe("inactive");
  });

  it("refreshes when the access token is missing but a refresh token exists", () => {
    const expiresAt = new Date(now.getTime() + 20 * 60 * 1000);
    expect(
      xeroConnectionRefreshDecision(
        { ...base, expiresAt, hasAccessToken: false },
        now
      )
    ).toBe("refresh");
  });

  it("is inactive when both the access and refresh tokens are missing", () => {
    const expiresAt = new Date(now.getTime() + 20 * 60 * 1000);
    expect(
      xeroConnectionRefreshDecision(
        { ...base, expiresAt, hasAccessToken: false, hasRefreshToken: false },
        now
      )
    ).toBe("inactive");
  });

  it("is inactive when revoked, disconnected, or stale", () => {
    const expiresAt = new Date(now.getTime() + 20 * 60 * 1000);
    expect(
      xeroConnectionRefreshDecision({ ...base, expiresAt, revokedAt: now }, now)
    ).toBe("inactive");
    expect(
      xeroConnectionRefreshDecision(
        { ...base, expiresAt, status: "disconnected" },
        now
      )
    ).toBe("inactive");
    expect(
      xeroConnectionRefreshDecision(
        { ...base, expiresAt, status: "stale" },
        now
      )
    ).toBe("inactive");
  });
});

describe("refreshXeroOAuthConnection", () => {
  const input = {
    clerkOrgId: "org_1",
    connectionId: "conn_1",
    organisationId: "11111111-1111-1111-1111-111111111111",
  };

  function mockStoredConnection() {
    const storedTokens = buildStoredTokenFields();
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce({
      disconnected_at: null,
      id: input.connectionId,
      refresh_token_auth_tag: storedTokens.refresh_token_auth_tag,
      refresh_token_encrypted: storedTokens.refresh_token_encrypted,
      refresh_token_iv: storedTokens.refresh_token_iv,
      revoked_at: null,
      status: "active",
      token_key_version: 1,
    });
  }

  it.each([
    ["missing access token", { expires_in: 1800, refresh_token: "refresh" }],
    [
      "empty refresh token",
      { access_token: "access", expires_in: 1800, refresh_token: "" },
    ],
    [
      "non-positive expiry",
      { access_token: "access", expires_in: 0, refresh_token: "refresh" },
    ],
    [
      "non-integer expiry",
      { access_token: "access", expires_in: 1.5, refresh_token: "refresh" },
    ],
  ])("rejects a %s in a successful token response", async (_name, body) => {
    mockStoredConnection();
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue(
        new Response(JSON.stringify(body), {
          headers: { "content-type": "application/json" },
          status: 200,
        })
      )
    );

    const result = await refreshXeroOAuthConnection(input);

    expect(result).toEqual({
      error: {
        code: "invalid_token_response",
        message: "Xero token response was invalid.",
      },
      ok: false,
    });
    expect(dbMock.xeroConnection.updateMany).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          last_error_code: "refresh_persist_failed",
          status: "active",
        }),
      })
    );
  });

  it("rejects a non-JSON successful token response", async () => {
    mockStoredConnection();
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue(
        new Response("not-json", {
          headers: { "content-type": "text/plain" },
          status: 200,
        })
      )
    );

    const result = await refreshXeroOAuthConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("invalid_token_response");
    }
  });

  it.each([
    ["stale", null, null],
    ["disconnected", new Date("2026-01-01T00:00:00.000Z"), null],
    ["active", null, new Date("2026-01-01T00:00:00.000Z")],
  ])(
    "does not exchange tokens for an inactive %s connection",
    async (status, disconnectedAt, revokedAt) => {
      const storedTokens = buildStoredTokenFields();
      dbMock.xeroConnection.findFirst.mockResolvedValueOnce({
        disconnected_at: disconnectedAt,
        id: input.connectionId,
        refresh_token_auth_tag: storedTokens.refresh_token_auth_tag,
        refresh_token_encrypted: storedTokens.refresh_token_encrypted,
        refresh_token_iv: storedTokens.refresh_token_iv,
        revoked_at: revokedAt,
        status,
        token_key_version: 1,
      });
      const fetchSpy = vi.fn();
      vi.stubGlobal("fetch", fetchSpy);

      const result = await refreshXeroOAuthConnection(input);

      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe("connection_inactive");
      }
      expect(fetchSpy).not.toHaveBeenCalled();
    }
  );

  it("classifies an invalid refresh token and marks the connection stale", async () => {
    mockStoredConnection();
    dbMock.xeroConnection.update.mockResolvedValueOnce({});
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        json: async () => ({ error: "invalid_grant" }),
        ok: false,
        status: 400,
      })
    );

    const result = await refreshXeroOAuthConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("refresh_token_invalid");
    }
    expect(dbMock.xeroConnection.updateMany).toHaveBeenCalledWith({
      data: {
        last_error_code: "refresh_token_invalid",
        last_error_message:
          "The Xero refresh token is no longer valid. Reconnect Xero.",
        stale_since: expect.any(Date),
        status: "stale",
      },
      where: {
        clerk_org_id: input.clerkOrgId,
        disconnected_at: null,
        id: input.connectionId,
        organisation_id: input.organisationId,
        revoked_at: null,
        status: "active",
      },
    });
  });

  it("classifies Xero's refresh_token_invalid alias and marks the connection stale", async () => {
    mockStoredConnection();
    dbMock.xeroConnection.update.mockResolvedValueOnce({});
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        json: async () => ({ error: "refresh_token_invalid" }),
        ok: false,
        status: 400,
      })
    );

    const result = await refreshXeroOAuthConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("refresh_token_invalid");
    }
    expect(dbMock.xeroConnection.updateMany).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          last_error_code: "refresh_token_invalid",
          status: "stale",
        }),
      })
    );
  });

  it.each(["unauthorized_client", "invalid_client"])(
    "classifies %s and marks the connection stale",
    async (errorCode) => {
      mockStoredConnection();
      dbMock.xeroConnection.update.mockResolvedValueOnce({});
      vi.stubGlobal(
        "fetch",
        vi.fn().mockResolvedValue({
          json: async () => ({ error: errorCode }),
          ok: false,
          status: 401,
        })
      );

      const result = await refreshXeroOAuthConnection(input);

      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe("client_credentials_invalid");
      }
      expect(dbMock.xeroConnection.updateMany).toHaveBeenCalledWith({
        data: {
          last_error_code: "client_credentials_invalid",
          last_error_message:
            "The Xero client credentials are no longer valid. Contact support.",
          stale_since: expect.any(Date),
          status: "stale",
        },
        where: {
          clerk_org_id: input.clerkOrgId,
          disconnected_at: null,
          id: input.connectionId,
          organisation_id: input.organisationId,
          revoked_at: null,
          status: "active",
        },
      });
    }
  );

  it("returns network_error for transient HTTP failures without marking stale", async () => {
    mockStoredConnection();
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        json: async () => ({ error: "invalid_client" }),
        ok: false,
        status: 503,
      })
    );

    const result = await refreshXeroOAuthConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("network_error");
    }
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ status: "stale" }),
      })
    );
  });

  it("returns network_error for dropped connections without marking stale", async () => {
    mockStoredConnection();
    vi.stubGlobal(
      "fetch",
      vi.fn().mockRejectedValue(new Error("socket reset"))
    );

    const result = await refreshXeroOAuthConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("network_error");
    }
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ status: "stale" }),
      })
    );
  });

  it("takes the advisory lock before a successful manual refresh", async () => {
    mockStoredConnection();
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        json: async () => ({
          access_token: "new-access-token",
          expires_in: 1800,
          refresh_token: "new-refresh-token",
        }),
        ok: true,
        status: 200,
      })
    );

    const result = await refreshXeroOAuthConnection(input);

    expect(result.ok).toBe(true);
    expect(dbMock.$transaction).toHaveBeenCalledTimes(1);
    expect(dbMock.$queryRaw).toHaveBeenCalledTimes(1);
    const [queryParts, connectionId] = dbMock.$queryRaw.mock.calls[0];
    expect(queryParts.join(" ")).toContain(
      "pg_advisory_xact_lock(hashtextextended("
    );
    expect(queryParts.join(" ")).toContain("::text AS acquired");
    expect(connectionId).toBe(input.connectionId);
    expect(dbMock.xeroConnection.findFirst).toHaveBeenCalledWith(
      expect.objectContaining({
        select: expect.objectContaining({
          refresh_token_auth_tag: true,
          refresh_token_encrypted: true,
          refresh_token_iv: true,
          token_key_version: true,
        }),
      })
    );
  });

  it("returns already_refreshed and does not mark the connection stale if the CAS update matches 0 rows", async () => {
    mockStoredConnection();
    dbMock.xeroConnection.updateMany.mockResolvedValueOnce({ count: 0 });
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        json: async () => ({
          access_token: "new-access-token",
          expires_in: 1800,
          refresh_token: "new-refresh-token",
        }),
        ok: true,
        status: 200,
      })
    );

    const result = await refreshXeroOAuthConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("already_refreshed");
    }
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalled();
  });

  it("recovers rotated credentials when the transaction fails after a successful token exchange", async () => {
    const storedTokens = buildStoredTokenFields();
    dbMock.xeroConnection.findFirst
      .mockResolvedValueOnce({
        disconnected_at: null,
        id: input.connectionId,
        refresh_token_auth_tag: storedTokens.refresh_token_auth_tag,
        refresh_token_encrypted: storedTokens.refresh_token_encrypted,
        refresh_token_iv: storedTokens.refresh_token_iv,
        revoked_at: null,
        status: "active",
        token_key_version: 1,
      })
      .mockResolvedValueOnce({
        disconnected_at: null,
        expires_at: new Date("2026-06-09T12:01:00.000Z"),
        refresh_token_encrypted: storedTokens.refresh_token_encrypted,
        revoked_at: null,
        status: "active",
      });
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        json: async () => ({
          access_token: "new-access-token",
          expires_in: 1800,
          refresh_token: "new-refresh-token",
        }),
        ok: true,
        status: 200,
      })
    );
    dbMock.xeroConnection.updateMany.mockRejectedValueOnce(
      new Error("Database transaction aborted.")
    );

    const result = await refreshXeroOAuthConnection(input);

    expect(result.ok).toBe(true);
    expect(dbMock.xeroConnection.updateMany).toHaveBeenLastCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          last_error_code: null,
          status: "active",
        }),
        where: expect.objectContaining({
          refresh_token_encrypted: storedTokens.refresh_token_encrypted,
          status: "active",
        }),
      })
    );
  });
});

describe("ensureFreshXeroConnection", () => {
  const input = {
    clerkOrgId: "org_1",
    connectionId: "conn_1",
    now: new Date("2026-06-09T12:00:00.000Z"),
    organisationId: "11111111-1111-1111-1111-111111111111",
  };

  it("returns organisation_not_found when the connection is missing", async () => {
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce(null);

    const result = await ensureFreshXeroConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("organisation_not_found");
    }
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalled();
  });

  it("does not refresh a token that is valid beyond the buffer", async () => {
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce({
      ...buildStoredTokenFields(),
      expires_at: new Date(input.now.getTime() + 20 * 60 * 1000),
      revoked_at: null,
      status: "active",
    });
    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);

    const result = await ensureFreshXeroConnection(input);

    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.refreshed).toBe(false);
    }
    expect(fetchSpy).not.toHaveBeenCalled();
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalled();
  });

  it("returns connection_inactive for a revoked connection", async () => {
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce({
      ...buildStoredTokenFields(),
      expires_at: new Date(input.now.getTime() + 20 * 60 * 1000),
      revoked_at: input.now,
      status: "active",
    });

    const result = await ensureFreshXeroConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("connection_inactive");
    }
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalled();
  });

  it("refreshes and re-persists the token before returning when near expiry", async () => {
    const storedTokens = buildStoredTokenFields();
    dbMock.xeroConnection.findFirst
      // ensureFreshXeroConnection: initial connection state (near expiry)
      .mockResolvedValueOnce({
        ...storedTokens,
        expires_at: new Date(input.now.getTime() + 60 * 1000),
        revoked_at: null,
        status: "active",
      })
      // ensureFreshXeroConnection: re-read inside the advisory lock.
      .mockResolvedValueOnce({
        ...storedTokens,
        expires_at: new Date(input.now.getTime() + 60 * 1000),
        revoked_at: null,
        status: "active",
      })
      // refreshXeroOAuthConnection: scoped encrypted refresh-token material.
      .mockResolvedValueOnce({
        disconnected_at: null,
        id: input.connectionId,
        refresh_token_auth_tag: storedTokens.refresh_token_auth_tag,
        refresh_token_encrypted: storedTokens.refresh_token_encrypted,
        refresh_token_iv: storedTokens.refresh_token_iv,
        revoked_at: null,
        status: "active",
      });
    dbMock.xeroConnection.updateMany.mockResolvedValueOnce({ count: 1 });

    const fetchSpy = vi.fn().mockResolvedValue({
      json: async () => ({
        access_token: "new-access-token",
        expires_in: 1800,
        refresh_token: "new-refresh-token",
      }),
      ok: true,
      status: 200,
    });
    vi.stubGlobal("fetch", fetchSpy);

    const result = await ensureFreshXeroConnection(input);

    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.refreshed).toBe(true);
    }
    // The token exchange happened and the new tokens were persisted before returning.
    expect(fetchSpy).toHaveBeenCalledTimes(1);
    expect(fetchSpy).toHaveBeenCalledWith(
      "https://identity.xero.com/connect/token",
      expect.objectContaining({ method: "POST" })
    );
    const requestBody = fetchSpy.mock.calls[0]?.[1]?.body;
    expect(requestBody).toBeInstanceOf(URLSearchParams);
    if (requestBody instanceof URLSearchParams) {
      expect(requestBody.get("refresh_token")).toBe("refresh-token");
    }
    expect(dbMock.xeroConnection.updateMany).toHaveBeenCalledTimes(1);
    const [[updateArg]] = dbMock.xeroConnection.updateMany.mock.calls;
    expect(updateArg.data.status).toBe("active");
    expect(updateArg.data.access_token_encrypted).not.toBe("");
    expect(updateArg.where).toEqual({
      clerk_org_id: input.clerkOrgId,
      disconnected_at: null,
      id: input.connectionId,
      organisation_id: input.organisationId,
      refresh_token_encrypted: storedTokens.refresh_token_encrypted,
      revoked_at: null,
      status: "active",
    });
    const [queryParts, connectionId] = dbMock.$queryRaw.mock.calls[0];
    expect(queryParts.join(" ")).toContain(
      "pg_advisory_xact_lock(hashtextextended("
    );
    expect(queryParts.join(" ")).toContain("::text AS acquired");
    expect(connectionId).toBe(input.connectionId);
    const [, lockedRead, refreshRead] =
      dbMock.xeroConnection.findFirst.mock.calls;
    expect(lockedRead?.[0].select).toEqual(
      expect.objectContaining({
        refresh_token_auth_tag: true,
        refresh_token_encrypted: true,
        refresh_token_iv: true,
        token_key_version: true,
      })
    );
    expect(refreshRead?.[0].select).toEqual(
      expect.objectContaining({
        refresh_token_auth_tag: true,
        refresh_token_encrypted: true,
        refresh_token_iv: true,
        token_key_version: true,
      })
    );
  });

  it("marks the connection stale when a proactive refresh gets invalid_grant", async () => {
    const storedTokens = buildStoredTokenFields();
    const staleConnection = {
      ...storedTokens,
      expires_at: new Date(input.now.getTime() + 60 * 1000),
      revoked_at: null,
      status: "active",
    };
    dbMock.xeroConnection.findFirst
      .mockResolvedValueOnce(staleConnection)
      .mockResolvedValueOnce(staleConnection)
      .mockResolvedValueOnce({
        disconnected_at: null,
        id: input.connectionId,
        refresh_token_auth_tag: storedTokens.refresh_token_auth_tag,
        refresh_token_encrypted: storedTokens.refresh_token_encrypted,
        refresh_token_iv: storedTokens.refresh_token_iv,
        revoked_at: null,
        status: "active",
      });
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        json: async () => ({ error: "invalid_grant" }),
        ok: false,
        status: 400,
      })
    );

    const result = await ensureFreshXeroConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("refresh_token_invalid");
    }
    expect(dbMock.xeroConnection.updateMany).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ status: "stale" }),
      })
    );
  });

  it("skips refresh inside the lock when another caller already refreshed", async () => {
    const storedTokens = buildStoredTokenFields();
    dbMock.xeroConnection.findFirst
      .mockResolvedValueOnce({
        ...storedTokens,
        expires_at: new Date(input.now.getTime() + 60 * 1000),
        revoked_at: null,
        status: "active",
      })
      .mockResolvedValueOnce({
        ...storedTokens,
        expires_at: new Date(input.now.getTime() + 20 * 60 * 1000),
        revoked_at: null,
        status: "active",
      });
    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);

    const result = await ensureFreshXeroConnection(input);

    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value).toEqual({
        expiresAt: new Date(input.now.getTime() + 20 * 60 * 1000),
        refreshed: false,
      });
    }
    expect(dbMock.$queryRaw).toHaveBeenCalledTimes(1);
    expect(fetchSpy).not.toHaveBeenCalled();
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalled();
  });

  it("recovers rotated credentials when proactive refresh persistence is ambiguous", async () => {
    const storedTokens = buildStoredTokenFields();
    dbMock.xeroConnection.findFirst
      .mockResolvedValueOnce({
        ...storedTokens,
        expires_at: new Date(input.now.getTime() + 60 * 1000),
        revoked_at: null,
        status: "active",
      })
      .mockResolvedValueOnce({
        ...storedTokens,
        expires_at: new Date(input.now.getTime() + 60 * 1000),
        revoked_at: null,
        status: "active",
      })
      .mockResolvedValueOnce({
        disconnected_at: null,
        id: input.connectionId,
        refresh_token_auth_tag: storedTokens.refresh_token_auth_tag,
        refresh_token_encrypted: storedTokens.refresh_token_encrypted,
        refresh_token_iv: storedTokens.refresh_token_iv,
        revoked_at: null,
        status: "active",
      })
      .mockResolvedValueOnce({
        disconnected_at: null,
        expires_at: new Date(input.now.getTime() + 60 * 1000),
        refresh_token_encrypted: storedTokens.refresh_token_encrypted,
        revoked_at: null,
        status: "active",
      });

    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        json: async () => ({
          access_token: "new-access-token",
          expires_in: 1800,
          refresh_token: "new-refresh-token",
        }),
        ok: true,
        status: 200,
      })
    );
    dbMock.xeroConnection.updateMany.mockRejectedValueOnce(
      new Error("Database connection timed out.")
    );

    const result = await ensureFreshXeroConnection(input);

    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.refreshed).toBe(true);
    }
    expect(dbMock.xeroConnection.updateMany).toHaveBeenLastCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ status: "active" }),
        where: expect.objectContaining({
          refresh_token_encrypted: storedTokens.refresh_token_encrypted,
          status: "active",
        }),
      })
    );
  });

  it("refreshes inside the lock when the locked re-read is still stale", async () => {
    const storedTokens = buildStoredTokenFields();
    dbMock.xeroConnection.findFirst
      .mockResolvedValueOnce({
        ...storedTokens,
        expires_at: new Date(input.now.getTime() + 60 * 1000),
        revoked_at: null,
        status: "active",
      })
      .mockResolvedValueOnce({
        ...storedTokens,
        expires_at: new Date(input.now.getTime() + 60 * 1000),
        revoked_at: null,
        status: "active",
      })
      .mockResolvedValueOnce({
        disconnected_at: null,
        id: input.connectionId,
        refresh_token_auth_tag: storedTokens.refresh_token_auth_tag,
        refresh_token_encrypted: storedTokens.refresh_token_encrypted,
        refresh_token_iv: storedTokens.refresh_token_iv,
        revoked_at: null,
        status: "active",
      });
    dbMock.xeroConnection.updateMany.mockResolvedValueOnce({ count: 1 });
    const fetchSpy = vi.fn().mockResolvedValue({
      json: async () => ({
        access_token: "new-access-token",
        expires_in: 1800,
        refresh_token: "new-refresh-token",
      }),
      ok: true,
      status: 200,
    });
    vi.stubGlobal("fetch", fetchSpy);

    const result = await ensureFreshXeroConnection(input);

    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.refreshed).toBe(true);
    }
    expect(fetchSpy).toHaveBeenCalledTimes(1);
    const requestBody = fetchSpy.mock.calls[0]?.[1]?.body;
    expect(requestBody).toBeInstanceOf(URLSearchParams);
    if (requestBody instanceof URLSearchParams) {
      expect(requestBody.get("refresh_token")).toBe("refresh-token");
    }
    expect(dbMock.xeroConnection.updateMany).toHaveBeenCalledTimes(1);
    const [[updateArg]] = dbMock.xeroConnection.updateMany.mock.calls;
    expect(updateArg.data.refresh_token_encrypted).not.toBe(
      storedTokens.refresh_token_encrypted
    );
  });

  it("serialises concurrent refresh checks so only the winner exchanges tokens", async () => {
    const storedTokens = buildStoredTokenFields();
    const staleConnection = {
      ...storedTokens,
      expires_at: new Date(input.now.getTime() + 60 * 1000),
      revoked_at: null,
      status: "active",
    };
    const freshConnection = {
      ...storedTokens,
      expires_at: new Date(input.now.getTime() + 20 * 60 * 1000),
      revoked_at: null,
      status: "active",
    };
    dbMock.xeroConnection.findFirst
      .mockResolvedValueOnce(staleConnection)
      .mockResolvedValueOnce(staleConnection)
      .mockResolvedValueOnce(staleConnection)
      .mockResolvedValueOnce({
        disconnected_at: null,
        id: input.connectionId,
        refresh_token_auth_tag: storedTokens.refresh_token_auth_tag,
        refresh_token_encrypted: storedTokens.refresh_token_encrypted,
        refresh_token_iv: storedTokens.refresh_token_iv,
        revoked_at: null,
        status: "active",
      })
      .mockResolvedValueOnce(freshConnection);
    dbMock.xeroConnection.updateMany.mockResolvedValueOnce({ count: 1 });

    let lockHeld = false;
    let releaseLock: (() => void) | undefined;
    dbMock.$queryRaw.mockImplementation(async () => {
      if (!lockHeld) {
        lockHeld = true;
        return [];
      }
      await new Promise<void>((resolve) => {
        releaseLock = resolve;
      });
      return [];
    });
    dbMock.$transaction.mockImplementation(async (callback) => {
      const result = await callback(dbMock);
      if (lockHeld) {
        lockHeld = false;
        releaseLock?.();
      }
      return result;
    });

    const fetchSpy = vi.fn().mockResolvedValue({
      json: async () => ({
        access_token: "new-access-token",
        expires_in: 1800,
        refresh_token: "new-refresh-token",
      }),
      ok: true,
      status: 200,
    });
    vi.stubGlobal("fetch", fetchSpy);

    const [first, second] = await Promise.all([
      ensureFreshXeroConnection(input),
      ensureFreshXeroConnection(input),
    ]);

    expect(first.ok).toBe(true);
    expect(second.ok).toBe(true);
    expect(fetchSpy).toHaveBeenCalledTimes(1);
    expect(dbMock.xeroConnection.updateMany).toHaveBeenCalledTimes(1);
  });

  it("returns unknown_error when acquiring the advisory lock fails", async () => {
    const storedTokens = buildStoredTokenFields();
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce({
      ...storedTokens,
      expires_at: new Date(input.now.getTime() + 60 * 1000),
      revoked_at: null,
      status: "active",
    });
    dbMock.$queryRaw.mockRejectedValueOnce(new Error("lock failed"));
    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);

    const result = await ensureFreshXeroConnection(input);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("unknown_error");
    }
    expect(fetchSpy).not.toHaveBeenCalled();
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalled();
  });
});

describe("disconnectXeroOAuthConnection", () => {
  const input = {
    clerkOrgId: "org_1",
    connectionId: "11111111-1111-4111-8111-111111111111",
    destructive: false,
    organisationId: "22222222-2222-4222-8222-222222222222",
  };

  function buildConnection(
    xeroAuthorisationConnectionId: null | string = "xero-connection-1"
  ) {
    return {
      ...buildStoredTokenFields(),
      disconnected_at: null,
      expires_at: new Date("2099-01-01T00:00:00.000Z"),
      id: input.connectionId,
      revoked_at: null,
      status: "active",
      xero_authorisation_connection_id: xeroAuthorisationConnectionId,
      xero_tenant: null,
    };
  }

  it("revokes the Xero connection before clearing local tokens", async () => {
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce(buildConnection());
    dbMock.xeroConnection.update.mockResolvedValueOnce({});
    const fetchSpy = vi
      .fn()
      .mockResolvedValueOnce(new Response(null, { status: 204 }));
    vi.stubGlobal("fetch", fetchSpy);

    const result = await disconnectXeroOAuthConnection(input);

    expect(fetchSpy).toHaveBeenCalledWith(
      "https://api.xero.com/connections/xero-connection-1",
      expect.objectContaining({ method: "DELETE" })
    );
    expect(result).toEqual({
      ok: true,
      value: { disconnected: true, remoteRevoked: true },
    });
    expect(dbMock.xeroConnection.update).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          access_token_encrypted: "",
          status: "disconnected",
        }),
      })
    );
  });

  it("preserves local tokens when the Xero revoke cannot be confirmed", async () => {
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce(buildConnection());
    dbMock.xeroConnection.update.mockResolvedValueOnce({});
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValueOnce(new Response(null, { status: 503 }))
    );

    const result = await disconnectXeroOAuthConnection(input);

    expect(result).toEqual({
      error: {
        code: "network_error",
        message: "Xero could not confirm the connection revocation. Try again.",
      },
      ok: false,
    });
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalled();
  });

  it("refreshes an expired access token before revoking and records the actor", async () => {
    const expired = {
      ...buildConnection(),
      expires_at: new Date("2020-01-01T00:00:00.000Z"),
    };
    const refreshed = buildConnection();
    dbMock.xeroConnection.findFirst
      .mockResolvedValueOnce(expired)
      .mockResolvedValueOnce(expired)
      .mockResolvedValueOnce(refreshed);
    dbMock.xeroConnection.update.mockResolvedValueOnce({});
    const fetchSpy = vi
      .fn()
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            access_token: "new-access-token",
            expires_in: 1800,
            refresh_token: "new-refresh-token",
          }),
          {
            headers: { "content-type": "application/json" },
            status: 200,
          }
        )
      )
      .mockResolvedValueOnce(new Response(null, { status: 204 }));
    vi.stubGlobal("fetch", fetchSpy);

    const result = await disconnectXeroOAuthConnection({
      ...input,
      performedByUserId: "user_1",
    });

    expect(result).toEqual({
      ok: true,
      value: { disconnected: true, remoteRevoked: true },
    });
    expect(fetchSpy).toHaveBeenCalledTimes(2);
    expect(dbMock.xeroConnection.update).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          disconnected_by_user_id: "user_1",
          status: "disconnected",
        }),
      })
    );
  });

  it("treats an already absent remote connection as safe to disconnect locally", async () => {
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce(buildConnection());
    dbMock.xeroConnection.update.mockResolvedValueOnce({});
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValueOnce(new Response(null, { status: 404 }))
    );

    const result = await disconnectXeroOAuthConnection(input);

    expect(result).toEqual({
      ok: true,
      value: { disconnected: true, remoteRevoked: false },
    });
    expect(dbMock.xeroConnection.update).toHaveBeenCalledOnce();
  });

  it("still revokes a stale permission connection when its access token is usable", async () => {
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce({
      ...buildConnection(),
      last_error_code: "xero_permission_denied",
      status: "stale",
    });
    dbMock.xeroConnection.update.mockResolvedValueOnce({});
    const fetchSpy = vi
      .fn()
      .mockResolvedValueOnce(new Response(null, { status: 204 }));
    vi.stubGlobal("fetch", fetchSpy);

    const result = await disconnectXeroOAuthConnection(input);

    expect(result.ok).toBe(true);
    expect(fetchSpy).toHaveBeenCalledOnce();
    expect(dbMock.xeroConnection.update).toHaveBeenCalledOnce();
  });

  it("preserves credentials when a stale connection cannot be revoked safely", async () => {
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce({
      ...buildConnection(),
      expires_at: new Date("2020-01-01T00:00:00.000Z"),
      last_error_code: "xero_permission_denied",
      status: "stale",
    });
    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);

    const result = await disconnectXeroOAuthConnection(input);

    expect(result).toEqual({
      error: {
        code: "connection_inactive",
        message:
          "Team Calendar could not confirm the Xero connection revocation. Reconnect Xero, then try disconnecting again.",
      },
      ok: false,
    });
    expect(fetchSpy).not.toHaveBeenCalled();
    expect(dbMock.xeroConnection.update).not.toHaveBeenCalled();
  });

  it("skips the remote revoke when no authorisation connection id is stored", async () => {
    dbMock.xeroConnection.findFirst.mockResolvedValueOnce(
      buildConnection(null)
    );
    dbMock.xeroConnection.update.mockResolvedValueOnce({});
    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);

    const result = await disconnectXeroOAuthConnection(input);

    expect(fetchSpy).not.toHaveBeenCalled();
    expect(result).toEqual({
      ok: true,
      value: { disconnected: true, remoteRevoked: false },
    });
    expect(dbMock.xeroConnection.update).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ access_token_encrypted: "" }),
      })
    );
  });
});

describe("completeXeroTenantSelection", () => {
  const sessionId = "90000000-0000-4000-8000-000000000001";
  const organisationId = "90000000-0000-4000-8000-000000000002";
  const connectionId = "90000000-0000-4000-8000-000000000003";
  const xeroTenantRowId = "90000000-0000-4000-8000-000000000004";
  const clerkOrgId = "org_xero_default_feed";
  const tenantId = "xero-tenant-1";

  beforeEach(() => {
    dbMock.xeroOAuthSession.findFirst.mockResolvedValue(buildPendingSession());
    dbMock.organisation.findMany.mockResolvedValue([]);
    dbMock.organisation.create.mockResolvedValue({ id: organisationId });
    dbMock.xeroConnection.upsert.mockResolvedValue({ id: connectionId });
    dbMock.xeroTenant.upsert.mockResolvedValue({ id: xeroTenantRowId });
    dbMock.xeroOAuthSession.update.mockResolvedValue({});
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue(
        new Response(
          JSON.stringify({
            Organisations: [{ CountryCode: "AU", Name: "Acme Payroll" }],
          }),
          { headers: { "Content-Type": "application/json" }, status: 200 }
        )
      )
    );
  });

  it("provisions the default feed when tenant selection creates an organisation", async () => {
    const result = await completeXeroTenantSelection({
      clerkOrgId,
      sessionId,
      tenantId,
      userId: "user_1",
    });

    expect(result).toMatchObject({
      ok: true,
      value: {
        connectionId,
        organisationId,
        xeroTenantId: xeroTenantRowId,
      },
    });
    expect(dbMock.organisation.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          clerk_org_id: clerkOrgId,
          country_code: "AU",
          name: "Acme Payroll",
        }),
      })
    );
    expect(feedMock.ensureDefaultCalendarFeed).toHaveBeenCalledWith({
      clerkOrgId,
      organisationId,
    });
    expect(
      availabilityMock.ensureDefaultPublicHolidaysForOrganisation
    ).toHaveBeenCalledWith({
      clerkOrgId,
      organisationId,
    });
    expect(dbMock.xeroConnection.upsert).toHaveBeenCalledWith(
      expect.objectContaining({
        create: expect.objectContaining({
          clerk_org_id: clerkOrgId,
          organisation_id: organisationId,
        }),
        where: { organisation_id: organisationId },
      })
    );
    expect(dbMock.xeroOAuthSession.updateMany).toHaveBeenCalledWith({
      data: { status: "completed" },
      where: {
        clerk_org_id: clerkOrgId,
        created_by_user_id: "user_1",
        expires_at: { gt: expect.any(Date) },
        id: sessionId,
        status: "pending",
      },
    });
    expect(dbMock.xeroOAuthSession.update).toHaveBeenCalledWith({
      data: expect.objectContaining({
        access_token_auth_tag: null,
        access_token_encrypted: "",
        access_token_iv: null,
        available_tenants_json: { tenants: [] },
        refresh_token_auth_tag: null,
        refresh_token_encrypted: "",
        refresh_token_iv: null,
        token_encrypted_at: null,
      }),
      where: { id: sessionId },
    });
  });

  it("allows only one caller to claim a pending OAuth session", async () => {
    dbMock.xeroOAuthSession.updateMany.mockResolvedValueOnce({ count: 0 });

    const result = await completeXeroTenantSelection({
      clerkOrgId,
      sessionId,
      tenantId,
      userId: "user_1",
    });

    expect(result).toEqual({
      error: {
        code: "session_not_found",
        message:
          "This Xero OAuth session has already been completed or is no longer available.",
      },
      ok: false,
    });
    expect(dbMock.organisation.create).not.toHaveBeenCalled();
    expect(dbMock.xeroConnection.upsert).not.toHaveBeenCalled();
    expect(dbMock.xeroTenant.upsert).not.toHaveBeenCalled();
  });

  it("rejects reconnecting an existing payroll entity to another Xero file", async () => {
    dbMock.xeroOAuthSession.findFirst.mockResolvedValue({
      ...buildPendingSession(),
      organisation_id: organisationId,
    });
    dbMock.organisation.findMany.mockResolvedValue([
      { country_code: "AU", id: organisationId },
    ]);
    dbMock.organisation.findFirst.mockResolvedValue({
      country_code: "AU",
      id: organisationId,
    });
    dbMock.xeroTenant.findFirst.mockResolvedValue({
      active_slot: 1,
      binding_generation: 1,
      xero_tenant_id: "XERO-AAA",
    });

    const result = await completeXeroTenantSelection({
      clerkOrgId,
      organisationId,
      sessionId,
      tenantId,
      userId: "user_1",
    });

    expect(result).toMatchObject({
      error: { code: "tenant_replacement_required" },
      ok: false,
    });
    expect(dbMock.xeroTenant.upsert).not.toHaveBeenCalled();
  });

  it("rejects an outdated binding generation", async () => {
    mockExistingSelection(3);
    dbMock.xeroTenant.findFirst.mockResolvedValueOnce({
      active_slot: 1,
      binding_generation: 4,
      xero_tenant_id: tenantId,
    });

    const result = await completeXeroTenantSelection({
      clerkOrgId,
      organisationId,
      sessionId,
      tenantId,
      userId: "user_1",
    });

    expect(result).toMatchObject({
      error: { code: "connection_changed" },
      ok: false,
    });
    expect(dbMock.xeroTenant.upsert).not.toHaveBeenCalled();
  });

  it("rejects a reservation held elsewhere without identifying its owner", async () => {
    mockExistingSelection(3);
    dbMock.xeroTenant.findFirst
      .mockResolvedValueOnce({
        active_slot: 1,
        binding_generation: 3,
        xero_tenant_id: tenantId,
      })
      .mockResolvedValueOnce({ id: "other-reservation" });

    const result = await completeXeroTenantSelection({
      clerkOrgId,
      organisationId,
      sessionId,
      tenantId,
      userId: "user_1",
    });

    expect(result).toMatchObject({
      error: { code: "tenant_binding_conflict" },
      ok: false,
    });
    if (!result.ok) {
      expect(result.error.message).not.toContain("other-reservation");
      expect(result.error.message).not.toContain(organisationId);
      expect(result.error.message).not.toContain(clerkOrgId);
      expect(result.error.message).not.toContain("user_1");
    }
    expect(dbMock.xeroTenant.upsert).not.toHaveBeenCalled();
  });

  it("reconnects to the same file without updating its external tenant ID", async () => {
    mockExistingSelection(3);
    dbMock.xeroTenant.findFirst.mockResolvedValueOnce({
      active_slot: 1,
      binding_generation: 3,
      xero_tenant_id: tenantId,
    });

    const result = await completeXeroTenantSelection({
      clerkOrgId,
      organisationId,
      sessionId,
      tenantId,
      userId: "user_1",
    });

    expect(result.ok).toBe(true);
    const upsert = dbMock.xeroTenant.upsert.mock.calls[0]?.[0];
    expect(upsert?.update).not.toHaveProperty("xero_tenant_id");
    expect(upsert?.update).toMatchObject({
      active_slot: 1,
      binding_generation: { increment: 1 },
    });
  });

  it.each(["NZ", "UK"])(
    "rejects an unsupported %s payroll tenant before persistence",
    async (countryCode) => {
      vi.stubGlobal(
        "fetch",
        vi
          .fn()
          .mockResolvedValue(
            new Response(
              JSON.stringify({ Organisations: [{ CountryCode: countryCode }] }),
              { headers: { "Content-Type": "application/json" }, status: 200 }
            )
          )
      );

      const result = await completeXeroTenantSelection({
        clerkOrgId,
        sessionId,
        tenantId,
        userId: "user_1",
      });

      expect(result).toEqual({
        error: {
          code: "invalid_country",
          message:
            "Team Calendar currently supports Australian Xero Payroll files only.",
        },
        ok: false,
      });
      expect(dbMock.organisation.create).not.toHaveBeenCalled();
      expect(dbMock.$transaction).not.toHaveBeenCalled();
      expect(dbMock.xeroConnection.upsert).not.toHaveBeenCalled();
      expect(dbMock.xeroTenant.upsert).not.toHaveBeenCalled();
      expect(dbMock.xeroOAuthSession.update).not.toHaveBeenCalled();
    }
  );

  it("keeps the completed tenant selection when default feed provisioning fails", async () => {
    feedMock.ensureDefaultCalendarFeed.mockResolvedValueOnce({
      error: {
        code: "unknown_error",
        message: "Failed to create default feed.",
      },
      ok: false,
    });

    const result = await completeXeroTenantSelection({
      clerkOrgId,
      sessionId,
      tenantId,
      userId: "user_1",
    });

    expect(result.ok).toBe(true);
    expect(dbMock.xeroConnection.upsert).toHaveBeenCalledOnce();
    expect(dbMock.xeroTenant.upsert).toHaveBeenCalledOnce();
    expect(dbMock.xeroOAuthSession.update).toHaveBeenCalledOnce();
  });

  it("succeeds tenant selection even when default holiday provisioning fails", async () => {
    availabilityMock.ensureDefaultPublicHolidaysForOrganisation.mockResolvedValueOnce(
      {
        error: {
          code: "internal",
          message: "Network error while calling Nager.Date API",
        },
        ok: false,
      }
    );

    const result = await completeXeroTenantSelection({
      clerkOrgId,
      sessionId,
      tenantId,
      userId: "user_1",
    });

    expect(result).toMatchObject({
      ok: true,
      value: {
        connectionId,
        organisationId,
        xeroTenantId: xeroTenantRowId,
      },
    });
    expect(dbMock.organisation.create).toHaveBeenCalled();
    expect(feedMock.ensureDefaultCalendarFeed).toHaveBeenCalled();
    expect(
      availabilityMock.ensureDefaultPublicHolidaysForOrganisation
    ).toHaveBeenCalledWith({
      clerkOrgId,
      organisationId,
    });
  });

  function buildPendingSession() {
    const accessToken = encryptXeroToken("access-token");
    const refreshToken = encryptXeroToken("refresh-token");

    return {
      access_token_auth_tag: accessToken.authTag,
      access_token_encrypted: accessToken.encrypted,
      access_token_iv: accessToken.iv,
      available_tenants_json: {
        tenants: [
          {
            connectionId: "xero-connection-1",
            tenantId,
            tenantName: "Acme Payroll",
          },
        ],
      },
      expected_binding_generation: null,
      expires_at: new Date("2026-07-07T00:15:00.000Z"),
      id: sessionId,
      organisation_id: null,
      refresh_token_auth_tag: refreshToken.authTag,
      refresh_token_encrypted: refreshToken.encrypted,
      refresh_token_iv: refreshToken.iv,
      return_to: "/settings/integrations/xero",
      token_expires_at: new Date("2026-07-07T00:30:00.000Z"),
    };
  }

  function mockExistingSelection(expectedGeneration: number) {
    dbMock.xeroOAuthSession.findFirst.mockResolvedValue({
      ...buildPendingSession(),
      expected_binding_generation: expectedGeneration,
      organisation_id: organisationId,
    });
    dbMock.organisation.findMany.mockResolvedValue([
      { country_code: "AU", id: organisationId },
    ]);
    dbMock.organisation.findFirst.mockResolvedValue({
      country_code: "AU",
      id: organisationId,
    });
  }
});

describe("scrubInactiveXeroOAuthSessionCredentials", () => {
  it("expires pending sessions and scrubs credentials from all terminal sessions", async () => {
    dbMock.xeroOAuthSession.updateMany
      .mockResolvedValueOnce({ count: 2 })
      .mockResolvedValueOnce({ count: 3 });
    const now = new Date("2026-08-29T00:00:00.000Z");

    const result = await scrubInactiveXeroOAuthSessionCredentials(now);

    expect(result).toEqual({ ok: true, value: { scrubbed: 5 } });
    expect(dbMock.xeroOAuthSession.updateMany).toHaveBeenNthCalledWith(1, {
      data: expect.objectContaining({
        access_token_encrypted: "",
        available_tenants_json: { tenants: [] },
        refresh_token_encrypted: "",
        status: "expired",
      }),
      where: { expires_at: { lte: now }, status: "pending" },
    });
    expect(dbMock.xeroOAuthSession.updateMany).toHaveBeenNthCalledWith(2, {
      data: expect.objectContaining({
        access_token_encrypted: "",
        available_tenants_json: { tenants: [] },
        refresh_token_encrypted: "",
      }),
      where: expect.objectContaining({
        status: { in: ["cancelled", "completed", "expired"] },
      }),
    });
  });
});

describe("markXeroConnectionStale", () => {
  it("cannot overwrite a disconnected or revoked lifecycle state", async () => {
    await markXeroConnectionStale({
      clerkOrgId: "org_1",
      connectionId: "connection_1",
      errorCode: "xero_permission_denied",
      errorMessage: "Permission denied.",
      organisationId: "00000000-0000-4000-8000-000000000001",
    });

    expect(dbMock.xeroConnection.updateMany).toHaveBeenCalledWith({
      data: expect.objectContaining({
        last_error_code: "xero_permission_denied",
        status: "stale",
      }),
      where: {
        clerk_org_id: "org_1",
        disconnected_at: null,
        id: "connection_1",
        organisation_id: "00000000-0000-4000-8000-000000000001",
        revoked_at: null,
        status: "active",
      },
    });
  });
});
